version: 2.1


jobs:  
  build-and-test:    
    docker:
      - image: sreedocker123/govstackmccapitestcircleci:latest
        auth:
          username: sreedocker123
          password: docker@123
    steps:          
      
      - run:
          name: Run Echo to test Path
          command: uvicorn main:app --reload  
      - run:
          name: Check API is Listening
          command: curl http://localhost:8000/home/

      - run:
          name: Run Pytest
          command: cd /app/test && pytest
    
    
workflows:  
  build-test-and-deploy:    
    jobs:      
      - build-and-test:
          filters:            
            branches:
              only:
                - master