version: 2.1


jobs:  
  build-and-test:    
    build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01
    steps:   
      - checkout       
      - run:
          name: Deploy MCC API and PyTest Containers
          command: docker-compose up -d 
      - run:
          name: Check Status of Containers
          command: docker ps
      
      - run:
          name: Test API Integration Scripts on MyAPI Container From PyTest Container
          command: docker exec -it pytest cd /app/test & ls
      

    
workflows:  
  build-test-and-deploy:    
    jobs:      
      - build-and-test:
          filters:            
            branches:
              only:
                - master